name: task - validate commit on master
on:
  push:
    branches: [ master ]

jobs:
  basic_job:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Check lint
        if: always()
        run: ./gradlew lint

      - name: Run Unit Tests
        if: always()
        run: ./gradlew testDebugUnitTest

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug
